shellEmulator: true
shamefullyHoist: true
enablePrePostScripts: true
strictPeerDependencies: true

registry: https://registry.npmmirror.com

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  prisma: true
